scene_detection:
  method: adaptive                # adaptive | content | threshold_params | histogram | hash
  min_scene_len: 7            # Alternative: Frames (nur falls Sekunden nicht gesetzt)
# min_scene_len_seconds: 1    # Mindestdauer einer Szene (Sek.)

transition:
  type: hard_cut       # (Deaktiviert) hard_cut | fade_in_out
  fade_duration: 1.0   # Fade-Dauer in Sekunden (nur bei fade_in_out)

output:
  download_dir: output          # Basis-Verzeichnis für Downloads
  temp_dir: temp_segments       # Zielordner für geschnittene Szenen
  merged_dir: merged_videos     # (Deaktiviert) Ausgabeordner für gemergte Gruppen
