scene_detection:
  method: adaptive                # adaptive | content | threshold_params | histogram | hash
  min_scene_len: 7               # Mindestlänge einer Szene in Sekunden

# Ähnlichkeitsbasierte Gruppierung (standardmäßig aktiviert)
grouping:
  enabled: true                 # Automatische Gruppierung standardmäßig aktiviert
  
  # Feature-Extraktions-Methode
  method: cnn                   # cnn | histogram | orb | sift | phash | audio (empfohlen: cnn)
  
  # Ähnlichkeitsbasierte Parameter
  min_similarity: 0.75          # 0.75 # Mindest-Ähnlichkeit für Gruppierung (0-1)
  min_group_size: 2             # Mindestanzahl Videos pro Gruppe
  orphan_threshold: 0         # Schwellwert für Einzelvideos (niedriger als min_similarity)
  similarity_metric: cosine     # cosine | euclidean | correlation (empfohlen: cosine)
  group_expansion_mode: average  # strict | average (Gruppenerweiterungslogik)

transition:
  type: hard_cut               # hard_cut (andere Optionen entfernt für Einfachheit)

output:
  download_dir: output          # Basis-Verzeichnis für Downloads
  temp_dir: temp_segments       # Zielordner für geschnittene Szenen
  merged_dir: merged_videos     # Ausgabeordner für gruppierte Videos
