###############################################
# Scene Detection Configuration
#
# method:
#   adaptive  - Rolling-average adaptive content change (robust bei Kamerabewegung)
#   content   - Feste Schwelle auf HSV-Änderung (klassische harte Schnitte)
#   threshold - Helligkeits-basierte Fades (fade in/out, dunkle Übergänge)
#   histogram - Y-Kanal Histogramm-Differenz (stabil bei Farb-/Lichtwechseln)
#   hash      - Perceptual Hash Differenzen (robust gegen kleine Pixeländerungen, aber langsamer)
#
# min_scene_len_seconds: Minimale Szenenlänge in Sekunden (überschreibt min_scene_len Frames)
# (Optional) min_scene_len: Minimale Szenenlänge in Frames (falls Sekunden nicht gesetzt)
#
# Für jede Methode kann ein Unter-Block existieren, dessen Werte die Defaults überschreiben.
# Nicht verwendete Blöcke können entfernt oder auskommentiert werden.
###############################################
scene_detection:
  method: hash            # adaptive | content | threshold | histogram | hash
  # min_scene_len_seconds: 1    # Mindestdauer einer Szene (Sek.)
  min_scene_len: 12         # Alternative: Frames (nur falls Sekunden nicht gesetzt)

  adaptive:
    adaptive_threshold: 3.0   # 3.0 /Ratio-Schwelle (niedriger = sensibler)
    window_width: 2           # Fensterbreite für gleitenden Durchschnitt
    min_content_val: 15.0     # Mindest-Content-Wert (Filter gegen Rauschen)

  content:
    threshold: 27.0           # 27.0 / Pixeländerungs-Schwelle (niedriger = mehr Schnitte)
    luma_only: false          # true = nur Helligkeit (stabiler, weniger Schnitte)

  threshold_params:
    threshold: 12             # 12 / Helligkeitsgrenze (0-255) für Fades
    fade_bias: 0.0            # -1..+1 verschiebt Schnittposition innerhalb des Fades
    add_final_scene: false    # true = fügt Szene am Videoende hinzu falls Fade-Out

  histogram:
    threshold: 0.05           # 0.05 /0..1 relative Differenz (kleiner = sensibler)
    bins: 256                 # Histogramm-Bins (höher = genauer, langsamer)

  hash:
    threshold: 0.450          # 0.395 / 0..1 Hamming-Distanz / (size*size) (kleiner = sensibler)
    size: 16                  # DCT Low-Frequency-Größe
    lowpass: 2                # 2 behält 1/2, 4 behält 1/4 der Frequenzen

grouping:
  similarity_threshold: 10  # (Derzeit deaktiviert) Hamming-Distanz für Gruppierung ähnlicher Segmente

transition:
  type: hard_cut       # (Deaktiviert) hard_cut | fade_in_out
  fade_duration: 1.0   # Fade-Dauer in Sekunden (nur bei fade_in_out)

output:
  temp_dir: temp_segments   # Zielordner für geschnittene Szenen
  merged_dir: merged_videos # (Deaktiviert) Ausgabeordner für gemergte Gruppen
